### PR TITLE
CO-15: Wartremover should error not warn

### PR DESCRIPTION
**Pull request by carlpulley**
- [x] Modify code with a `CI` conditional
---
- [x] Ready for review

### CODE REVIEW

**Review by amirkarimi — APPROVED** [review]

**Comment by fommil** [comment]
We disagree with this in our project. We prefer warning not error, with fatal warnings. Otherwise it negatively affects developer workflow.

**Comment by fommil** [comment]
Umm, This isn't even necessary because we already have fatal warnings so everything gets lifted. Am I missing something?

**Comment by carlpulley** [comment]
I can see value in using warning for developer cycles (i.e. when `CI` is not set).

So I guess the key question is what is preferred in CI? I'd have thought that for CI error would surely be the preferred setting?

**Comment by carlpulley** [comment]
From what I can see, the miss appears to be with the setting of `CI`?

**Comment by fommil** [comment]
ok, looks like you figured this out re: `CI`

**Pull request closed without merging**
