### PR TITLE
Increase max line length to 120 characters

### PR DESCRIPTION
**Pull request by by-dam**

### CODE REVIEW

**Review by simonsouter — APPROVED** [review]

**Comment by fommil** [comment]
I disagree with 120 characters because it makes the text too wide to do a 3 way merge.

80 characters allows for two windows of text to be open at the same time.

**Review by Slakah — APPROVED** [review]

**Review by tudorzgureanu — APPROVED** [review]

**Comment by fommil** [comment]
madness

**Comment by simonsouter** [comment]
time to upgrade your green screen :)

**Comment by fommil** [comment]
if you ever work on a project alongside me, my constant complaints will make you seriously regret this decision :wink: 

Honestly, it will never end.

**Pull request merged**
