### PR TITLE
CO-170: Ensure docker-compose commands can be isolated by project name

### PR DESCRIPTION
**Pull request by carlpulley**
- [x] Add in env. var. override to docker-compose up and down commands
- [x] Update Jenkins file to use a random project name
---
- [x] Ready for review

### CODE REVIEW

**Review by fommil — APPROVED** [review]

**Comment by fommil** [comment]
can you please push the change with support for the docker name to the v1.x branch? We should also change the base image to `openjdk:8-jre` since the alpine images don't support a lot of libs with binaries (e.g. aws)

**Comment by carlpulley** [comment]
Adding this PR to the `v1.x` branch is not a problem - I'll generate a PR against that branch.

I'd say that the image change here is specific to your use case. Hence I'd suggest that we make this change on a per project basis (e.g. within the `project/ProjectPlugin.scala` file) by modifying the `dockerImage` setting directly.

**Review by ferhtaydn — APPROVED** [review]

**Comment by carlpulley** [comment]
@fommil PR #38 should address your issue.

**Comment by fommil** [comment]
cheers. We've already changed the base image, but I'd argue that the "dumbest" solution should be the default, with people able to override it with a more optimal image as needed. We found problems with a number of libraries in alpine that were (naughtily) using binaries.

**Pull request merged**
